tmgmt.translator.settings.xtm_connect:
  type: tmgmt_xtm_connect_settings

tmgmt_xtm_connect_settings:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    url:
      type: string
      label: Translation API endpoint url.
    url_usage:
      type: string
      label: Usage API endpoint url.
    auth_key:
      type: string
      label: Auth key
